version: '3.1'

volumes:
  svip_pgdata:
  svip_esdata:
  seqrepo:

services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
         - "svip_pgdata:/var/lib/postgresql/data" # for now we're storing pg data to a volume
         - ./svip_db_backups:/backups
         - ./db_config:/docker-entrypoint-initdb.d
    ports:
      - "30432:5432" # FIXME: dev access port, remove later
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDB=${POSTGRES_DB}

  api:
    # image: "svip_api:latest"
    build: ./svip_api
    # restart: always
    volumes:
      - ./svip_api:/app
    ports:
     - "8085:8085"
     - "8889:8889"  # jupyterlab port
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD

  local_uta:
    image: biocommons/uta:uta_20171026
    restart: always
    ports:
      - "15032:5432"

  harvester:
    build: ./g2p-aggregator/harvester
    working_dir: /app
    environment:
      - BIOONTOLOGY_API_KEY=7951121e-3c26-4db1-9f82-476d928dfbc2
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - UTA_DB_URL=postgresql://anonymous@local_uta/uta/uta_20171026
      - HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/2018-08-21
    volumes:
      - './g2p-aggregator/harvester:/app'
      - './g2p-aggregator/data:/data'
      - './outputs:/output'
      - '/usr/local/share/seqrepo:/usr/local/share/seqrepo'
    depends_on:
      - db
      # - api
      - local_uta
