version: '3.1'

volumes:
  svip_pgdata:
  svip_esdata:
  seqrepo:

services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
         - "svip_pgdata:/var/lib/postgresql/data" # for now we're storing pg data to a volume
         - ./svip_db_backups:/backups
         - ./db_config:/docker-entrypoint-initdb.d
    ports:
      - "30432:5432" # FIXME: dev access port, remove later
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDB=${POSTGRES_DB}

  api:
    # image: "svip_api:latest"
    build: ./svip_api
    # restart: always
    volumes:
      - ./svip_api:/app
    ports:
     - "8085:8085"
     - "8889:8889"  # jupyterlab port
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD
