version: '3.5'

services:
  api:
    build:
      context: ./svip_api
      args:
        requirefile: requirements.prod.txt
    restart: always
    environment:
      # - POSTGRES_DB=svip_api
      - USE_DEV_SERVER=
      - DJANGO_SETTINGS_MODULE=svip_server.settings.production

  frontend:
    build: ./tupro_report_frontend
    command: bash -c "npm run build"
    restart: 'no'
    volumes:
      - 'web_built:/tupro_report_frontend/build'
    environment:
      - 'VUE_APP_API_URL=http://localhost/api'
