version: '3.1'

volumes:
  svip_pgdata:
  svip_esdata:

services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
         - "svip_pgdata:/var/lib/postgresql/data" # for now we're storing pg data to a volume
    ports:
      - "30432:5432" # FIXME: dev access port, remove later
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  svip_api:
    # image: "svip_api:latest"
    build: ./svip_api
    # restart: always
    volumes:
      - ./svip_api:/app
    ports:
     - "8085:8085"
     - "8889:8889"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD

  local_uta:
    image: biocommons/uta:uta_20171026
    ports:
      - "15032:5432"

  harvester:
    build: ./g2p-aggregator/harvester
    working_dir: /app
    environment:
      - BIOONTOLOGY_API_KEY=7951121e-3c26-4db1-9f82-476d928dfbc2
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - UTA_DB_URL=postgresql://anonymous@local_uta/uta/uta_20171026
    volumes:
      - './g2p-aggregator/harvester:/app'
      - './g2p-aggregator/data:/data'
      - './outputs:/output'
    depends_on:
      - db
      - svip_api
      - local_uta

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
  #   container_name: elasticsearch
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - 'svip_esdata:/usr/share/elasticsearch/data'
  #   ports:
  #     - 9200:9200

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.5.1
  #   ports:
  #    - "5601:5601"
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   depends_on:
  #     - elasticsearch
