version: '3.1'

services:
  local_uta:
    image: biocommons/uta:uta_20171026
    restart: always
    ports:
      - "15032:5432"

  harvester:
    build: ./g2p-aggregator/harvester
    working_dir: /app
    environment:
      - BIOONTOLOGY_API_KEY=7951121e-3c26-4db1-9f82-476d928dfbc2
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - UTA_DB_URL=postgresql://anonymous@local_uta/uta/uta_20171026
      - HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/2018-08-21
    volumes:
      - './g2p-aggregator/harvester:/app'
      - './g2p-aggregator/data:/data'
      - './outputs:/output'
      - '/usr/local/share/seqrepo:/usr/local/share/seqrepo'
    depends_on:
      - db
      # - api
      - local_uta
