version: '3.5'

# generic compose config where nginx is the entrypoint
# site-specific configs should use this config and additionaly one from ./sites, e.g.:
# docker-compose -f docker-compose.yml -f compose/prod.yml -f compose/sites/svip-dev.yml "$@"

services:
  nginx:
    ports:
      - '8020:80'
      
  api:
    build:
      context: ./svip_api
      args:
        requirefile: requirements.prod.txt
    volumes:
      - api_static:/app/static
    environment:
      # - POSTGRES_DB=svip_api
      - USE_DEV_SERVER=
      - DJANGO_SETTINGS_MODULE=svip_server.settings.production

  frontend:
    build:
      context: ./svip-o-vue
      dockerfile: Dockerfile
      target: install-deps
    restart: 'no'
    environment:
      - 'VUE_APP_API_URL=http://localhost:8020/api/v1/'
