# note that the following variables are defined per-host in /etc/ansible/hosts:
# docker_bin: location of the 'docker' executable on that host
# dcompose_bin: location of the 'docker-compose' script on that host
# svip_dir: location of the SVIP root directory (i.e., the coordinator repo root)

---
- hosts: source
  tasks:
    - name: dump database to backups folder
      shell: >
        {{ docker_bin }} exec -it
        -e PGHOST=localhost
        -e PGUSER=postgres
        -e PGPASSWORD=postgres
        $( {{ dcompose_bin }} ps -q db )
        sh -c "pg_dump -F c -d svip_api > /backups/svip_api_{{ansible_date_time.date}}.dump"
      args:
        chdir: "{{ svip_dir }}"
        creates: "{{ svip_dir }}/svip_db_backups/svip_api_{{ansible_date_time.date}}.dump"
    - name: copy dump from source to local machine
      fetch:
        src: "{{ svip_dir }}/svip_db_backups/svip_api_{{ansible_date_time.date}}.dump"
        dest: ./staging/
        flat: yes

- hosts: sinks
  tasks:
    - name: copy db dump to all sinks
      copy:
        src: "./staging/svip_api_{{ansible_date_time.date}}.dump"
        dest: "{{ svip_dir }}/svip_db_backups/"
    - name: stop the api container, if it's running
      shell: "{{ dcompose_bin }} stop api"
      args:
        chdir: "{{ svip_dir }}"
    - name: ensure the db container is running
      shell: "{{ dcompose_bin }} up -d db"
      args:
        chdir: "{{ svip_dir }}"
    - name: load dump from source into db
      shell: >
        {{ docker_bin }} exec -it
        -e PGHOST=localhost
        -e PGUSER=postgres
        -e PGPASSWORD=postgres
        $( {{ dcompose_bin }} ps -q db)
        sh -c "dropdb svip_api && createdb svip_api && pg_restore -e -F c -d svip_api /backups/svip_api_{{ansible_date_time.date}}.dump"
      args:
        chdir: "{{ svip_dir }}"
    - name: restart the api container
      shell: "{{ dcompose_bin }} up -d api"
      args:
        chdir: "{{ svip_dir }}"
