version: "3.5"

services:
  api:
    build:
      args:
        http_proxy: http://172.17.0.1:18184
        https_proxy: http://172.17.0.1:18184
  nginx:
    ports:
      - "443:443"
      - "80:80"
    volumes:
      # - "${PWD}/service_config/nginx/sites/without_ssl.nginx:/etc/nginx/conf.d/svip.nginx:ro"
      - "${PWD}/service_config/nginx/sites/with_ssl.nginx:/etc/nginx/conf.d/svip.nginx:ro"
      - /var/vhosts/cert-store/vital-it.ch/fullchain.pem:/etc/pki/tls/certs/host.crt.pem
      - /var/vhosts/cert-store/vital-it.ch/privkey.pem:/etc/pki/tls/private/host.privkey.pem

  frontend:
    build:
      args:
        http_proxy: http://172.17.0.1:18184
        https_proxy: http://172.17.0.1:18184
    environment:
      - "VUE_APP_API_URL=/api/v1/"
